kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: simple-backend-canary
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: simple
        role: backend
        env: canary
    spec:
      containers:
      - name: backend
        image: gcr.io/dpe-dev-e1296334/simple-image:v1.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /test
            port: 8080
        env:
        - name: COMPONENT
          value: backend
        - name: VERSION
          value: canary
        ports:
        - name: backend
          containerPort: 8080